sudo: false
language: python

python:
  - "2.7"

install:
    - pip install tox-travis
    - pip install coveralls
    - pip install -r requirements.txt

script:
    - tox

after_success:
    - coveralls
